### ISSUE TITLE
Admin cannot open Support Request

### ISSUE THREAD

**Issue by lassnj** [center-for-learning-management/moodle-local_edusupport#11]
Manager Susanne passed an issue to 2nd level support with the Mail-Address support@lernmanagement.at
Julia L. tried to open the issue with her admin account. Error: You do not have permission to view this issue.

**Comment by rschrenk** [comment]
Basically - the script checked if you are in the supportteam. The Admin-Account of JuliaL is not. I added that also siteadmins can view all issues. Should work now since 48a7c7958c86876fcd063d06b29cc4af1be99698

**Comment by lassnj** [comment]
Admin JuliaL. still gets permission denied, when trying to open https://t1.eduvidual.org/local/edusupport/issue.php?d=11

**Comment by rschrenk** [comment]
This is not very surprising. Discussion 11 is no open issue. As an admin you can view it in the forum directly, but the eduSupport-Plugin only shows issues. Where have you found that link? If you go the the "issues"-Page from the left panel, it is not listed...

**Comment by rschrenk** [comment]
The error message is now more specific. The "Access denied" error only appears if the user is no site admin and does not belong to the support team. If the discussion is no open issue a new error message appears. The user can follow a link to the original discussion (and access capabilities are checked there) or back to the issues overview page.

Introduced in d257516421b06db1729056b9c39c2f523b042521
